/** Declaration file generated by dts-gen */

export = markdown_it_toc_done_right

declare function markdown_it_toc_done_right(md: any, options: any): any

declare namespace markdown_it_toc_done_right {
  const prototype: {}
}
